version: '3'

services:
  solargraph:
    build: .
    platform: linux/amd64
    environment:
      TZ: 'Asia/Tokyo'
      BUNDLE_PATH: /bundle/vendor
    command: /bin/ash -c "bundle exec solargraph socket --host=0.0.0.0 --port=7658"
    ports:
      - 7658:7658
    environment:
      BUNDLE_PATH: /bundle/vendor
    volumes:
      - .:/app
      - bundle_path:/bundle

volumes:
  bundle_path:
